name: Docker Image CI for Sign Feature

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repo
      - uses: actions/checkout@v4

      # 2) Register QEMU emulators so ARM binaries run under emulation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      # 3) Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 4) Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: halem10
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # 5) Build & push the ARM64 image
      - name: Build & push ARM64 image
        uses: docker/build-push-action@v4
        with:
          context: .            # your app folder
          file: DockerFile    # path to Dockerfile
          platforms: linux/arm64,linux/amd64                           # target architecture
          push: true
          tags: halem10/test_docker_picamer:1.0                    # your Docker Hub repo:tag
